# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MVVMArchitectureWithCombine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMArchitectureWithCombine
pod 'Kingfisher', '~> 6.0'

  target 'MVVMArchitectureWithCombineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMArchitectureWithCombineUITests' do
    # Pods for testing
  end

end
