# Uncomment the next line to define a global platform for your project
#
 platform :ios, '14.5'

target 'MVVMArchitectureWithRxswift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMArchitectureWithRxswift

    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
     pod 'Kingfisher', '~> 7.0'
  target 'MVVMArchitectureWithRxswiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMArchitectureWithRxswiftUITests' do
    # Pods for testing
  end

end
