# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'VIPERArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 6.0'
  # Pods for VIPERArchitecture

  target 'VIPERArchitectureTests' do
    inherit! :search_paths
  
    
     
  end

  target 'VIPERArchitectureUITests' do
    # Pods for testing
  end

end
